# Generated by Django 5.0.4 on 2024-04-23 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='入职时间'),
            preserve_default=False,
        ),
    ]
